includes:
  - configs/cluster_local.yaml
  - configs/cluster_multi.yaml

database: tpcds_100g
similarity_threshold: 0.2

target_system: spark

# Path directories
paths:
  log_dir: log
  data_dir: mock/data
  history_dir: mock/history
  target: tpcds_100g
  save_dir: results

# Method-related arguments
method_args:
  random_kwargs:
    seed: 42
    rand_prob: 0.15
    rand_mode: ran

  tl_args:
    topk: 3

  ws_args:
    init_num: 4
    topk: 20
    inner_surrogate_model: prf

  cp_args:
    strategy: none
    topk: 25
    kde_coverage: 0.8
    top_ratio: 0.6

  scheduler_kwargs:
    R: 27
    eta: 3

# Config spaces
config_spaces:
  config_space: configs/space/huge_space.json
  expert_space: configs/space/expert_space.json